### PR TITLE
Pep8 Formatting

### PR DESCRIPTION
**Pull request by osintowl**
Went from ~600 pep8 violations to 181 (most of which are too long of
lines)

### CODE REVIEW

**Comment by orlikoski** [comment]
Have you done any testing on the code to make sure the functions all work?

**Comment by orlikoski** [comment]
I think this is great work. It'll just require testing to make sure all the functions still work as intended as there were a lot of changes

**Comment by osintowl** [comment]
I'm doing some manual testing now i'll keep you updated. None of this should be breaking changes but i'll let you know asap.

**Comment by osintowl** [comment]
Everything I normally do works as expected. I had no issues with it on my Mac.

**Comment by orlikoski** [comment]
I understand that's how it normally works. I want to spend some time testing, or hearing about how you tested, to ensure all the functions work. 

For example, the code in https://github.com/orlikoski/CDQR/commit/2a537dae6d18035f06f1fa319edc383f00b6c186 required me to do https://github.com/orlikoski/CDQR/commit/021c66a26cb312b59d91f6c50f66400d6b398180 in order to get it working fully.

I want to be extra cautious to catch things prior to pushing to master now.

Would you be interested in helping me put together some build tests?  It would make this process much easier / faster for everyone.

**Comment by osintowl** [comment]
Yes totally cool. I would love to help put together some build tests. I’ll start digging into this. Have had some serious life changing events but want to help out with this.

**Comment by orlikoski** [comment]
Moving this merge into a dev branch that will enable us to test without merging to master

**Review by orlikoski — APPROVED** [review]
Merging to dev branch to enable testing

**Pull request merged**
